export const modalStyle = {
  position: 'absolute',
  top: '45%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: 'fit-content',
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: '30px 40px',
  display: 'inline-flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  gap: '10px',
  borderRadius: '20px',
};

export const bottomModalStyle = {
  position: 'absolute' as 'absolute',
  top: 'auto',
  bottom: 0,
  transform: 'translate(-50%, 0)',
  width: '100%',
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: '20px',
  display: 'inline-flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  gap: '10px',
  borderRadius: '20px 20px 0 0',
  backgroundColor: 'white',
  height: '510px',
};
